    - name: Install all required dependencies
      apt: 
        name: "{{ item }}" 
        state: present
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip

    - name: Make sure pymysql is present
      pip:
        name: pymysql
        state: present